export const countriesWithRegions = [
  { country: 'Afghanistan', region: 'Asia' },
  { country: 'Africa', region: 'Global' },
  { country: 'Africa (GCP)', region: 'Global' },
  { country: 'Albania', region: 'Europe' },
  { country: 'Algeria', region: 'Africa' },
  { country: 'Andorra', region: 'Europe' },
  { country: 'Angola', region: 'Africa' },
  { country: 'Anguilla', region: 'North America' },
  { country: 'Antarctica', region: 'Antarctica' },
  { country: 'Antigua and Barbuda', region: 'North America' },
  { country: 'Argentina', region: 'South America' },
  { country: 'Armenia', region: 'Asia' },
  { country: 'Aruba', region: 'North America' },
  { country: 'Asia', region: 'Global' },
  { country: 'Asia (GCP)', region: 'Global' },
  { country: 'Asia (excl. China and India)', region: 'Global' },
  { country: 'Australia', region: 'Oceania' },
  { country: 'Austria', region: 'Europe' },
  { country: 'Azerbaijan', region: 'Asia' },
  { country: 'Bahamas', region: 'North America' },
  { country: 'Bahrain', region: 'Middle East' },
  { country: 'Bangladesh', region: 'Asia' },
  { country: 'Barbados', region: 'North America' },
  { country: 'Belarus', region: 'Europe' },
  { country: 'Belgium', region: 'Europe' },
  { country: 'Belize', region: 'North America' },
  { country: 'Benin', region: 'Africa' },
  { country: 'Bermuda', region: 'North America' },
  { country: 'Bhutan', region: 'Asia' },
  { country: 'Bolivia', region: 'South America' },
  { country: 'Bonaire Sint Eustatius and Saba', region: 'North America' },
  { country: 'Bosnia and Herzegovina', region: 'Europe' },
  { country: 'Botswana', region: 'Africa' },
  { country: 'Brazil', region: 'South America' },
  { country: 'British Virgin Islands', region: 'North America' },
  { country: 'Brunei', region: 'Asia' },
  { country: 'Bulgaria', region: 'Europe' },
  { country: 'Burkina Faso', region: 'Africa' },
  { country: 'Burundi', region: 'Africa' },
  { country: 'Cambodia', region: 'Asia' },
  { country: 'Cameroon', region: 'Africa' },
  { country: 'Canada', region: 'North America' },
  { country: 'Cape Verde', region: 'Africa' },
  { country: 'Central African Republic', region: 'Africa' },
  { country: 'Central America (GCP)', region: 'Global' },
  { country: 'Chad', region: 'Africa' },
  { country: 'Chile', region: 'South America' },
  { country: 'China', region: 'Asia' },
  { country: 'Christmas Island', region: 'Oceania' },
  { country: 'Colombia', region: 'South America' },
  { country: 'Comoros', region: 'Africa' },
  { country: 'Congo', region: 'Africa' },
  { country: 'Cook Islands', region: 'Oceania' },
  { country: 'Costa Rica', region: 'North America' },
  { country: "Cote d'Ivoire", region: 'Africa' },
  { country: 'Croatia', region: 'Europe' },
  { country: 'Cuba', region: 'North America' },
  { country: 'Curacao', region: 'North America' },
  { country: 'Cyprus', region: 'Europe' },
  { country: 'Czechia', region: 'Europe' },
  { country: 'Democratic Republic of Congo', region: 'Africa' },
  { country: 'Denmark', region: 'Europe' },
  { country: 'Djibouti', region: 'Africa' },
  { country: 'Dominica', region: 'North America' },
  { country: 'Dominican Republic', region: 'North America' },
  { country: 'East Timor', region: 'Asia' },
  { country: 'Ecuador', region: 'South America' },
  { country: 'Egypt', region: 'Africa' },
  { country: 'El Salvador', region: 'North America' },
  { country: 'Equatorial Guinea', region: 'Africa' },
  { country: 'Eritrea', region: 'Africa' },
  { country: 'Estonia', region: 'Europe' },
  { country: 'Eswatini', region: 'Africa' },
  { country: 'Ethiopia', region: 'Africa' },
  { country: 'Europe', region: 'Global' },
  { country: 'Europe (GCP)', region: 'Global' },
  { country: 'Europe (excl. EU-27)', region: 'Global' },
  { country: 'Europe (excl. EU-28)', region: 'Global' },
  { country: 'European Union (27)', region: 'Global' },
  { country: 'European Union (28)', region: 'Global' },
  { country: 'Faroe Islands', region: 'Europe' },
  { country: 'Fiji', region: 'Oceania' },
  { country: 'Finland', region: 'Europe' },
  { country: 'France', region: 'Europe' },
  { country: 'French Polynesia', region: 'Oceania' },
  { country: 'Gabon', region: 'Africa' },
  { country: 'Gambia', region: 'Africa' },
  { country: 'Georgia', region: 'Asia' },
  { country: 'Germany', region: 'Europe' },
  { country: 'Ghana', region: 'Africa' },
  { country: 'Greece', region: 'Europe' },
  { country: 'Greenland', region: 'North America' },
  { country: 'Grenada', region: 'North America' },
  { country: 'Guatemala', region: 'North America' },
  { country: 'Guinea', region: 'Africa' },
  { country: 'Guinea-Bissau', region: 'Africa' },
  { country: 'Guyana', region: 'South America' },
  { country: 'Haiti', region: 'North America' },
  { country: 'High-income countries', region: 'Global' },
  { country: 'Honduras', region: 'North America' },
  { country: 'Hong Kong', region: 'Asia' },
  { country: 'Hungary', region: 'Europe' },
  { country: 'Iceland', region: 'Europe' },
  { country: 'India', region: 'Asia' },
  { country: 'Indonesia', region: 'Asia' },
  { country: 'International aviation', region: 'Global' },
  { country: 'International shipping', region: 'Global' },
  { country: 'International transport', region: 'Global' },
  { country: 'Iran', region: 'Middle East' },
  { country: 'Iraq', region: 'Middle East' },
  { country: 'Ireland', region: 'Europe' },
  { country: 'Israel', region: 'Middle East' },
  { country: 'Italy', region: 'Europe' },
  { country: 'Jamaica', region: 'North America' },
  { country: 'Japan', region: 'Asia' },
  { country: 'Jordan', region: 'Middle East' },
  { country: 'Kazakhstan', region: 'Asia' },
  { country: 'Kenya', region: 'Africa' },
  { country: 'Kiribati', region: 'Oceania' },
  { country: 'Kosovo', region: 'Europe' },
  { country: 'Kuwait', region: 'Middle East' },
  { country: 'Kuwaiti Oil Fires', region: 'Other' },
  { country: 'Kuwaiti Oil Fires (GCP)', region: 'Other' },
  { country: 'Kyrgyzstan', region: 'Asia' },
  { country: 'Laos', region: 'Asia' },
  { country: 'Latvia', region: 'Europe' },
  { country: 'Least developed countries (Jones et al.)', region: 'Global' },
  { country: 'Lebanon', region: 'Middle East' },
  { country: 'Lesotho', region: 'Africa' },
  { country: 'Liberia', region: 'Africa' },
  { country: 'Libya', region: 'Africa' },
  { country: 'Liechtenstein', region: 'Europe' },
  { country: 'Lithuania', region: 'Europe' },
  { country: 'Low-income countries', region: 'Global' },
  { country: 'Lower-middle-income countries', region: 'Global' },
  { country: 'Luxembourg', region: 'Europe' },
  { country: 'Macao', region: 'Asia' },
  { country: 'Madagascar', region: 'Africa' },
  { country: 'Malawi', region: 'Africa' },
  { country: 'Malaysia', region: 'Asia' },
  { country: 'Maldives', region: 'Asia' },
  { country: 'Mali', region: 'Africa' },
  { country: 'Malta', region: 'Europe' },
  { country: 'Marshall Islands', region: 'Oceania' },
  { country: 'Mauritania', region: 'Africa' },
  { country: 'Mauritius', region: 'Africa' },
  { country: 'Mexico', region: 'North America' },
  { country: 'Micronesia (country)', region: 'Oceania' },
  { country: 'Middle East (GCP)', region: 'Global' },
  { country: 'Moldova', region: 'Europe' },
  { country: 'Monaco', region: 'Europe' },
  { country: 'Mongolia', region: 'Asia' },
  { country: 'Montenegro', region: 'Europe' },
  { country: 'Montserrat', region: 'North America' },
  { country: 'Morocco', region: 'Africa' },
  { country: 'Mozambique', region: 'Africa' },
  { country: 'Myanmar', region: 'Asia' },
  { country: 'Namibia', region: 'Africa' },
  { country: 'Nauru', region: 'Oceania' },
  { country: 'Nepal', region: 'Asia' },
  { country: 'Netherlands', region: 'Europe' },
  { country: 'New Caledonia', region: 'Oceania' },
  { country: 'New Zealand', region: 'Oceania' },
  { country: 'Nicaragua', region: 'North America' },
  { country: 'Niger', region: 'Africa' },
  { country: 'Nigeria', region: 'Africa' },
  { country: 'Niue', region: 'Oceania' },
  { country: 'Non-OECD (GCP)', region: 'Global' },
  { country: 'North America', region: 'Global' },
  { country: 'North America (GCP)', region: 'Global' },
  { country: 'North America (excl. USA)', region: 'Global' },
  { country: 'North Korea', region: 'Asia' },
  { country: 'North Macedonia', region: 'Europe' },
  { country: 'Norway', region: 'Europe' },
  { country: 'OECD (GCP)', region: 'Global' },
  { country: 'OECD (Jones et al.)', region: 'Global' },
  { country: 'Oceania', region: 'Global' },
  { country: 'Oceania (GCP)', region: 'Global' },
  { country: 'Oman', region: 'Middle East' },
  { country: 'Pakistan', region: 'Asia' },
  { country: 'Palau', region: 'Oceania' },
  { country: 'Palestine', region: 'Middle East' },
  { country: 'Panama', region: 'North America' },
  { country: 'Papua New Guinea', region: 'Oceania' },
  { country: 'Paraguay', region: 'South America' },
  { country: 'Peru', region: 'South America' },
  { country: 'Philippines', region: 'Asia' },
  { country: 'Poland', region: 'Europe' },
  { country: 'Portugal', region: 'Europe' },
  { country: 'Qatar', region: 'Middle East' },
  { country: 'Romania', region: 'Europe' },
  { country: 'Russia', region: 'Europe' },
  { country: 'Rwanda', region: 'Africa' },
  { country: 'Ryukyu Islands', region: 'Asia' },
  { country: 'Ryukyu Islands (GCP)', region: 'Asia' },
  { country: 'Saint Helena', region: 'Africa' },
  { country: 'Saint Kitts and Nevis', region: 'North America' },
  { country: 'Saint Lucia', region: 'North America' },
  { country: 'Saint Pierre and Miquelon', region: 'North America' },
  { country: 'Saint Vincent and the Grenadines', region: 'North America' },
  { country: 'Samoa', region: 'Oceania' },
  { country: 'San Marino', region: 'Europe' },
  { country: 'Sao Tome and Principe', region: 'Africa' },
  { country: 'Saudi Arabia', region: 'Middle East' },
  { country: 'Senegal', region: 'Africa' },
  { country: 'Serbia', region: 'Europe' },
  { country: 'Seychelles', region: 'Africa' },
  { country: 'Sierra Leone', region: 'Africa' },
  { country: 'Singapore', region: 'Asia' },
  { country: 'Sint Maarten (Dutch part)', region: 'North America' },
  { country: 'Slovakia', region: 'Europe' },
  { country: 'Slovenia', region: 'Europe' },
  { country: 'Solomon Islands', region: 'Oceania' },
  { country: 'Somalia', region: 'Africa' },
  { country: 'South Africa', region: 'Africa' },
  { country: 'South America', region: 'Global' },
  { country: 'South America (GCP)', region: 'Global' },
  { country: 'South Korea', region: 'Asia' },
  { country: 'South Sudan', region: 'Africa' },
  { country: 'Spain', region: 'Europe' },
  { country: 'Sri Lanka', region: 'Asia' },
  { country: 'Sudan', region: 'Africa' },
  { country: 'Suriname', region: 'South America' },
  { country: 'Sweden', region: 'Europe' },
  { country: 'Switzerland', region: 'Europe' },
  { country: 'Syria', region: 'Middle East' },
  { country: 'Taiwan', region: 'Asia' },
  { country: 'Tajikistan', region: 'Asia' },
  { country: 'Tanzania', region: 'Africa' },
  { country: 'Thailand', region: 'Asia' },
  { country: 'Togo', region: 'Africa' },
  { country: 'Tonga', region: 'Oceania' },
  { country: 'Trinidad and Tobago', region: 'North America' },
  { country: 'Tunisia', region: 'Africa' },
  { country: 'Turkey', region: 'Europe' },
  { country: 'Turkmenistan', region: 'Asia' },
  { country: 'Turks and Caicos Islands', region: 'North America' },
  { country: 'Tuvalu', region: 'Oceania' },
  { country: 'Uganda', region: 'Africa' },
  { country: 'Ukraine', region: 'Europe' },
  { country: 'United Arab Emirates', region: 'Middle East' },
  { country: 'United Kingdom', region: 'Europe' },
  { country: 'United States', region: 'North America' },
  { country: 'Upper-middle-income countries', region: 'Global' },
  { country: 'Uruguay', region: 'South America' },
  { country: 'Uzbekistan', region: 'Asia' },
  { country: 'Vanuatu', region: 'Oceania' },
  { country: 'Vatican', region: 'Europe' },
  { country: 'Venezuela', region: 'South America' },
  { country: 'Vietnam', region: 'Asia' },
  { country: 'Wallis and Futuna', region: 'Oceania' },
  { country: 'World', region: 'Global' },
  { country: 'Yemen', region: 'Middle East' },
  { country: 'Zambia', region: 'Africa' },
  { country: 'Zimbabwe', region: 'Africa' },
];
