export const countriesWithRegions = [
  { country: 'Afghanistan', region: 'Asia' },
  { country: 'Africa', region: 'Global' },
  { country: 'Albania', region: 'Europe' },
  { country: 'Algeria', region: 'Africa' },
  { country: 'Andorra', region: 'Europe' },
  { country: 'Angola', region: 'Africa' },
  { country: 'Anguilla', region: 'North America' },
  { country: 'Antarctica', region: 'Antarctica' },
  { country: 'Argentina', region: 'South America' },
  { country: 'Armenia', region: 'Asia' },
  { country: 'Aruba', region: 'North America' },
  { country: 'Asia', region: 'Global' },
  { country: 'Australia', region: 'Oceania' },
  { country: 'Austria', region: 'Europe' },
  { country: 'Azerbaijan', region: 'Asia' },
  { country: 'Bahamas', region: 'North America' },
  { country: 'Bahrain', region: 'Middle East' },
  { country: 'Bangladesh', region: 'Asia' },
  { country: 'Barbados', region: 'North America' },
  { country: 'Belarus', region: 'Europe' },
  { country: 'Belgium', region: 'Europe' },
  { country: 'Belize', region: 'North America' },
  { country: 'Benin', region: 'Africa' },
  { country: 'Bermuda', region: 'North America' },
  { country: 'Bhutan', region: 'Asia' },
  { country: 'Bolivia', region: 'South America' },
  { country: 'Botswana', region: 'Africa' },
  { country: 'Brazil', region: 'South America' },
  { country: 'Brunei', region: 'Asia' },
  { country: 'Bulgaria', region: 'Europe' },
  { country: 'Burundi', region: 'Africa' },
  { country: 'Cambodia', region: 'Asia' },
  { country: 'Cameroon', region: 'Africa' },
  { country: 'Canada', region: 'North America' },
  { country: 'Chad', region: 'Africa' },
  { country: 'Chile', region: 'South America' },
  { country: 'China', region: 'Asia' },
  { country: 'Colombia', region: 'South America' },
  { country: 'Comoros', region: 'Africa' },
  { country: 'Congo', region: 'Africa' },
  { country: 'Croatia', region: 'Europe' },
  { country: 'Cuba', region: 'North America' },
  { country: 'Curacao', region: 'North America' },
  { country: 'Cyprus', region: 'Europe' },
  { country: 'Czechia', region: 'Europe' },
  { country: 'Denmark', region: 'Europe' },
  { country: 'Djibouti', region: 'Africa' },
  { country: 'Dominica', region: 'North America' },
  { country: 'Ecuador', region: 'South America' },
  { country: 'Egypt', region: 'Africa' },
  { country: 'Eritrea', region: 'Africa' },
  { country: 'Estonia', region: 'Europe' },
  { country: 'Eswatini', region: 'Africa' },
  { country: 'Ethiopia', region: 'Africa' },
  { country: 'Europe', region: 'Global' },
  { country: 'Fiji', region: 'Oceania' },
  { country: 'Finland', region: 'Europe' },
  { country: 'France', region: 'Europe' },
  { country: 'Gabon', region: 'Africa' },
  { country: 'Gambia', region: 'Africa' },
  { country: 'Georgia', region: 'Asia' },
  { country: 'Germany', region: 'Europe' },
  { country: 'Ghana', region: 'Africa' },
  { country: 'Greece', region: 'Europe' },
  { country: 'Greenland', region: 'North America' },
  { country: 'Grenada', region: 'North America' },
  { country: 'Guatemala', region: 'North America' },
  { country: 'Guinea', region: 'Africa' },
  { country: 'Guinea-Bissau', region: 'Africa' },
  { country: 'Guyana', region: 'South America' },
  { country: 'Haiti', region: 'North America' },
  { country: 'Honduras', region: 'North America' },
  { country: 'Hungary', region: 'Europe' },
  { country: 'Iceland', region: 'Europe' },
  { country: 'India', region: 'Asia' },
  { country: 'Indonesia', region: 'Asia' },
  { country: 'Iran', region: 'Middle East' },
  { country: 'Iraq', region: 'Middle East' },
  { country: 'Ireland', region: 'Europe' },
  { country: 'Israel', region: 'Middle East' },
  { country: 'Italy', region: 'Europe' },
  { country: 'Jamaica', region: 'North America' },
  { country: 'Japan', region: 'Asia' },
  { country: 'Jordan', region: 'Middle East' },
  { country: 'Kazakhstan', region: 'Asia' },
  { country: 'Kenya', region: 'Africa' },
  { country: 'Kiribati', region: 'Oceania' },
  { country: 'Kosovo', region: 'Europe' },
  { country: 'Kuwait', region: 'Middle East' },
  { country: 'Kyrgyzstan', region: 'Asia' },
  { country: 'Laos', region: 'Asia' },
  { country: 'Latvia', region: 'Europe' },
  { country: 'Lebanon', region: 'Middle East' },
  { country: 'Lesotho', region: 'Africa' },
  { country: 'Liberia', region: 'Africa' },
  { country: 'Libya', region: 'Africa' },
  { country: 'Liechtenstein', region: 'Europe' },
  { country: 'Lithuania', region: 'Europe' },
  { country: 'Luxembourg', region: 'Europe' },
  { country: 'Macao', region: 'Asia' },
  { country: 'Madagascar', region: 'Africa' },
  { country: 'Malawi', region: 'Africa' },
  { country: 'Malaysia', region: 'Asia' },
  { country: 'Maldives', region: 'Asia' },
  { country: 'Mali', region: 'Africa' },
  { country: 'Malta', region: 'Europe' },
  { country: 'Mauritania', region: 'Africa' },
  { country: 'Mauritius', region: 'Africa' },
  { country: 'Mexico', region: 'North America' },
  { country: 'Moldova', region: 'Europe' },
  { country: 'Monaco', region: 'Europe' },
  { country: 'Mongolia', region: 'Asia' },
  { country: 'Montenegro', region: 'Europe' },
  { country: 'Montserrat', region: 'North America' },
  { country: 'Morocco', region: 'Africa' },
  { country: 'Mozambique', region: 'Africa' },
  { country: 'Myanmar', region: 'Asia' },
  { country: 'Namibia', region: 'Africa' },
  { country: 'Nauru', region: 'Oceania' },
  { country: 'Nepal', region: 'Asia' },
  { country: 'Netherlands', region: 'Europe' },
  { country: 'Nicaragua', region: 'North America' },
  { country: 'Niger', region: 'Africa' },
  { country: 'Nigeria', region: 'Africa' },
  { country: 'Niue', region: 'Oceania' },
  { country: 'Norway', region: 'Europe' },
  { country: 'Oceania', region: 'Global' },
  { country: 'Oman', region: 'Middle East' },
  { country: 'Pakistan', region: 'Asia' },
  { country: 'Palau', region: 'Oceania' },
  { country: 'Palestine', region: 'Middle East' },
  { country: 'Panama', region: 'North America' },
  { country: 'Paraguay', region: 'South America' },
  { country: 'Peru', region: 'South America' },
  { country: 'Philippines', region: 'Asia' },
  { country: 'Poland', region: 'Europe' },
  { country: 'Portugal', region: 'Europe' },
  { country: 'Qatar', region: 'Middle East' },
  { country: 'Romania', region: 'Europe' },
  { country: 'Russia', region: 'Europe' },
  { country: 'Rwanda', region: 'Africa' },
  { country: 'Samoa', region: 'Oceania' },
  { country: 'Senegal', region: 'Africa' },
  { country: 'Serbia', region: 'Europe' },
  { country: 'Seychelles', region: 'Africa' },
  { country: 'Singapore', region: 'Asia' },
  { country: 'Slovakia', region: 'Europe' },
  { country: 'Slovenia', region: 'Europe' },
  { country: 'Somalia', region: 'Africa' },
  { country: 'Spain', region: 'Europe' },
  { country: 'Sudan', region: 'Africa' },
  { country: 'Suriname', region: 'South America' },
  { country: 'Sweden', region: 'Europe' },
  { country: 'Switzerland', region: 'Europe' },
  { country: 'Syria', region: 'Middle East' },
  { country: 'Taiwan', region: 'Asia' },
  { country: 'Tajikistan', region: 'Asia' },
  { country: 'Tanzania', region: 'Africa' },
  { country: 'Thailand', region: 'Asia' },
  { country: 'Togo', region: 'Africa' },
  { country: 'Tonga', region: 'Oceania' },
  { country: 'Tunisia', region: 'Africa' },
  { country: 'Turkey', region: 'Europe' },
  { country: 'Turkmenistan', region: 'Asia' },
  { country: 'Tuvalu', region: 'Oceania' },
  { country: 'Uganda', region: 'Africa' },
  { country: 'Ukraine', region: 'Europe' },
  { country: 'Uruguay', region: 'South America' },
  { country: 'Uzbekistan', region: 'Asia' },
  { country: 'Vanuatu', region: 'Oceania' },
  { country: 'Vatican', region: 'Europe' },
  { country: 'Venezuela', region: 'South America' },
  { country: 'Vietnam', region: 'Asia' },
  { country: 'World', region: 'Global' },
  { country: 'Yemen', region: 'Middle East' },
  { country: 'Zambia', region: 'Africa' },
  { country: 'Zimbabwe', region: 'Africa' },
];
